#!/bin/bash

SEARCH_DIR=${1:-.}
SELECTED_DIR=$(find "$SEARCH_DIR" -type d | fzf --height 20% --border --prompt="Select a directory: ")

if [ -d "$SELECTED_DIR/.venv" ]; then
    echo "venv found activating it"
    source "$SELECTED_DIR/.venv/bin/activate"
else
    echo "venv not found"
fi

(cd "$SELECTED_DIR" && session)
