#!/bin/bash

if [ "$#" -eq 0 ]; then
    session="${PWD##*/}"
elif [ "$#" -eq 1 ]; then
    session="$1"
else
    echo "Too many parameters for the session name, use only one"
    echo "Example:"
    echo "> session work"
    exit 1
fi

if tmux has-session -t "$session" 2>/dev/null; then
    echo "Session '$session' already exists. Attaching to it."
    tmux attach-session -t "$session"
else
    if [ -f "${PWD}/.venv/bin/activate" ]; then
        source "${PWD}/.venv/bin/activate"
    fi

    tmux new-session -d -s "$session"
    tmux new-window -t "$session":2
    tmux send-keys -t "$session":2 "nvim ." C-m
    tmux attach-session -t "$session":2
fi
